export interface LandingEvent {
  id:          string;
  slug:        string;
  title:       string;
  category:    string;
  eyebrow:     string;
  imageUrl:    string;
  price:       string;
  minPrice:    number;
  isFree:      boolean;
  date:        string;
  location:    string;
  scarcity?:   { state: string; label: string };
  friendCount?: number;
}

export const LANDING_EVENTS: LandingEvent[] = [
  {
    id:          "karnival-kingdom",
    slug:        "karnival-kingdom-2026",
    title:       "Karnival Kingdom",
    category:    "Music",
    eyebrow:     "LA PALM BEACH · APR 25",
    imageUrl:    "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80",
    price:       "GHS 200",
    minPrice:    200,
    isFree:      false,
    date:        "Sat, Apr 25 · 4:00 PM",
    location:    "La Palm Royal Beach, Accra",
    scarcity:    { state: "selling_fast", label: "Selling fast" },
    friendCount: 38,
  },
  {
    id:          "rapperholic-2026",
    slug:        "rapperholic-2026",
    title:       "Rapperholic 2026",
    category:    "Music",
    eyebrow:     "SARKODIE · GRAND ARENA",
    imageUrl:    "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=400&q=75",
    price:       "GHS 250",
    minPrice:    250,
    isFree:      false,
    date:        "Thu, Dec 25 · 8:00 PM",
    location:    "Grand Arena, Accra",
    scarcity:    { state: "selling_fast", label: "Selling fast" },
    friendCount: 94,
  },
  {
    id:          "chale-wote-2026",
    slug:        "chale-wote-street-art-festival-2026",
    title:       "Chale Wote Street Art Festival",
    category:    "Arts",
    eyebrow:     "JAMES TOWN · AUGUST",
    imageUrl:    "https://images.unsplash.com/photo-1551799517-eb8f03cb5e6a?auto=format&fit=crop&w=400&q=75",
    price:       "Free",
    minPrice:    0,
    isFree:      true,
    date:        "Aug 15 – 17 · All day",
    location:    "James Town, Accra",
    friendCount: 67,
  },
  {
    id:          "accra-food-festival",
    slug:        "accra-food-festival-2026",
    title:       "Accra Food Festival",
    category:    "Food",
    eyebrow:     "100 PARK · INDEPENDENCE AVE",
    imageUrl:    "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=400&q=75",
    price:       "GHS 80",
    minPrice:    80,
    isFree:      false,
    date:        "Sep 19 – 21 · 10:00 AM",
    location:    "Independence Ave, Accra",
    friendCount: 51,
  },
  {
    id:          "tidal-rave",
    slug:        "tidal-rave-accra",
    title:       "Tidal Rave",
    category:    "Music",
    eyebrow:     "LABADI BEACH",
    imageUrl:    "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=400&q=75",
    price:       "GHS 180",
    minPrice:    180,
    isFree:      false,
    date:        "Sat, Jul 12 · 4:00 PM",
    location:    "Labadi Beach, Accra",
    friendCount: 28,
  },
  {
    id:          "jazz-alliance-francaise",
    slug:        "jazz-world-music-festival-accra",
    title:       "Jazz & World Music Festival",
    category:    "Arts",
    eyebrow:     "ALLIANCE FRANÇAISE · ACCRA",
    imageUrl:    "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=400&q=75",
    price:       "GHS 120",
    minPrice:    120,
    isFree:      false,
    date:        "Apr 22 – 25 · 7:00 PM",
    location:    "Alliance Française, Accra",
    friendCount: 19,
  },
  {
    id:          "bhim-festival",
    slug:        "bhim-festival-2026",
    title:       "Bhim Festival",
    category:    "Music",
    eyebrow:     "STONEBWOY · DEC 24",
    imageUrl:    "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?auto=format&fit=crop&w=400&q=75",
    price:       "GHS 300",
    minPrice:    300,
    isFree:      false,
    date:        "Wed, Dec 24 · 7:00 PM",
    location:    "Grand Arena, Accra",
    scarcity:    { state: "selling_fast", label: "Going fast" },
    friendCount: 72,
  },
  {
    id:          "osu-night-market",
    slug:        "osu-night-market",
    title:       "Osu Night Market",
    category:    "Food",
    eyebrow:     "OXFORD STREET · OSU",
    imageUrl:    "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=400&q=75",
    price:       "Free",
    minPrice:    0,
    isFree:      true,
    date:        "Every Friday · 6:00 PM",
    location:    "Oxford Street, Osu",
    friendCount: 33,
  },
  {
    id:          "sip-paint",
    slug:        "sip-and-paint-night",
    title:       "Sip & Paint Night",
    category:    "Arts",
    eyebrow:     "AIRPORT RESIDENTIAL",
    imageUrl:    "https://images.unsplash.com/photo-1536924940846-227afb31e2a5?auto=format&fit=crop&w=400&q=75",
    price:       "GHS 120",
    minPrice:    120,
    isFree:      false,
    date:        "Sat, Apr 19 · 6:00 PM",
    location:    "Airport Residential, Accra",
    friendCount: 9,
  },
  {
    id:          "kumasi-creative",
    slug:        "kumasi-creative-club",
    title:       "Kumasi Creative Club",
    category:    "Arts",
    eyebrow:     "WORKSHOP AND SALON",
    imageUrl:    "https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?auto=format&fit=crop&w=400&q=75",
    price:       "GHS 95",
    minPrice:    95,
    isFree:      false,
    date:        "Sat, May 10 · 4:00 PM",
    location:    "Nhyiaeso, Kumasi",
    friendCount: 14,
  },
  {
    id:          "build-ghana",
    slug:        "build-ghana-summit",
    title:       "Build Ghana Summit",
    category:    "Tech",
    eyebrow:     "EAST LEGON · MAY",
    imageUrl:    "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=400&q=75",
    price:       "GHS 50",
    minPrice:    50,
    isFree:      false,
    date:        "Fri, May 9 · 9:00 AM",
    location:    "East Legon, Accra",
    friendCount: 41,
  },
  {
    id:          "ghana-ocean-festival",
    slug:        "ghana-ocean-festival-2026",
    title:       "Ghana Ocean Festival",
    category:    "Community",
    eyebrow:     "ALLIANCE FRANÇAISE · JUNE",
    imageUrl:    "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&w=400&q=75",
    price:       "Free",
    minPrice:    0,
    isFree:      true,
    date:        "Wed, Jun 3 · All day",
    location:    "Alliance Française, Accra",
    friendCount: 22,
  },
];

export interface TickerEvent {
  category: string;
  name:     string;
  location: string;
  signal:   string;
}

export const TICKER_EVENTS: TickerEvent[] = [
  { category: "Music",     name: "Karnival Kingdom",              location: "La Palm Beach",           signal: "Selling fast" },
  { category: "Music",     name: "Rapperholic 2026",              location: "Grand Arena",             signal: "Dec 25"       },
  { category: "Arts",      name: "Chale Wote Street Art Festival",location: "James Town",              signal: "Free"         },
  { category: "Food",      name: "Accra Food Festival",           location: "Independence Ave",        signal: "Sep 19–21"    },
  { category: "Music",     name: "Tidal Rave",                    location: "Labadi Beach",            signal: "Jul 12"       },
  { category: "Arts",      name: "Jazz & World Music Festival",   location: "Alliance Française",      signal: "Apr 22"       },
  { category: "Music",     name: "Bhim Festival",                 location: "Grand Arena",             signal: "Going fast"   },
  { category: "Food",      name: "Osu Night Market",              location: "Oxford Street, Osu",      signal: "Every Friday" },
  { category: "Tech",      name: "Build Ghana Summit",            location: "East Legon",              signal: "May 9"        },
  { category: "Community", name: "Ghana Ocean Festival",          location: "Alliance Française",      signal: "Free"         },
];

export const CATEGORY_COLORS: Record<string, string> = {
  Music:      "#7c3aed",
  Tech:       "#2563eb",
  Food:       "#d97706",
  Arts:       "#be185d",
  Sports:     "#059669",
  Networking: "#0891b2",
  Education:  "#b45309",
  Community:  "#5b21b6",
};
